services:
  etl:
    build: .
    container_name: finances-etl
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    container_name: finances-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  postgres_data: